### ISSUE TITLE
能否 问一下 list2Xls 最多能导入多少行数据呢

### ISSUE THREAD

**Issue by f292265656** [abel533/EasyXls#2]
使用 public static boolean list2Xls(List<?> list, String xmlPath, String filePath, String fileName) 这个方法的时候，6W多条数据和以下都正常，到了8W左右就会不正常，返回是true，可是文件并没有内容，打开还需要选择格式，能问问是怎么回事吗？ 感激不尽

**Comment by abel533** [comment]
xls最多6万多行

**Comment by f292265656** [comment]
好的，谢谢了，昨天查到大致是这个原因了，所以说如果存储更多行数据的话就不能直接用这个了是吗

**Comment by abel533** [comment]
不能用，或者拆分成多个

**Comment by f292265656** [comment]
了解了，谢谢～
